stages:
  - build

docker-image-build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t "$CI_REGISTRY_USER"/docker-sui .
    - docker push "$CI_REGISTRY_USER"/docker-sui
